[tools.claude-code]
path = ".claude"
# Note: hooks and mcp-servers merge into configuration files (no file installation)
resources = { agents = { path = "agents", flatten = true }, commands = { path = "commands", flatten = true }, hooks = { merge-target = ".claude/settings.local.json" }, mcp-servers = { merge-target = ".mcp.json" }, scripts = { path = "scripts", flatten = false }, snippets = { path = "snippets", flatten = false }, skills = { path = "skills", flatten = true } }

[commands]
checkpoint = { path = "local-deps/claude/commands/checkpoint.md" }
commit = { path = "local-deps/claude/commands/commit.md" }
execute = { path = "local-deps/claude/commands/execute.md" }
fact-check-docs = { path = "local-deps/claude/commands/fact-check-docs.md" }
gh-pr-create = { path = "local-deps/claude/commands/gh-pr-create.md" }
lint = { path = "local-deps/claude/commands/lint.md" }
pr-self-review = { path = "local-deps/claude/commands/pr-self-review.md" }
squash = { path = "local-deps/claude/commands/squash.md" }
update-all = { path = "local-deps/claude/commands/update-all.md" }
update-claude = { path = "local-deps/claude/commands/update-claude.md" }
update-docs = { path = "local-deps/claude/commands/update-docs.md" }
update-docstrings = { path = "local-deps/claude/commands/update-docstrings.md" }
opencode-checkpoint = { path = "local-deps/opencode/command/checkpoint.md", tool = "opencode" }
opencode-commit = { path = "local-deps/opencode/command/commit.md", tool = "opencode" }
opencode-execute = { path = "local-deps/opencode/command/execute.md", tool = "opencode" }
opencode-fact-check-docs = { path = "local-deps/opencode/command/fact-check-docs.md", tool = "opencode" }
opencode-gh-pr-create = { path = "local-deps/opencode/command/gh-pr-create.md", tool = "opencode" }
opencode-lint = { path = "local-deps/opencode/command/lint.md", tool = "opencode" }
opencode-pr-self-review = { path = "local-deps/opencode/command/pr-self-review.md", tool = "opencode" }
opencode-squash = { path = "local-deps/opencode/command/squash.md", tool = "opencode" }
opencode-update-all = { path = "local-deps/opencode/command/update-all.md", tool = "opencode" }
opencode-update-claude = { path = "local-deps/opencode/command/update-claude.md", tool = "opencode" }
opencode-update-docs = { path = "local-deps/opencode/command/update-docs.md", tool = "opencode" }
opencode-update-docstrings = { path = "local-deps/opencode/command/update-docstrings.md", tool = "opencode" }

# Add your script dependencies here
# Example: build = { source = "official", path = "scripts/build.sh" }
[scripts]

# Add your hook dependencies here
# Example: pre-commit = { source = "official", path = "hooks/pre-commit.json" }
[hooks]
agpm-update = { path = "local-deps/claude/hooks/agpm-update.json" }

# Add your MCP server dependencies here
# Example: filesystem = { source = "official", path = "mcp-servers/filesystem.json" }
[mcp-servers]

# Add your skill dependencies here
# Example: my-skill = { source = "official", path = "skills/my-skill", version = "v1.0.0" }
[skills]
