[package]
name = "ccpm"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Claude Code Package Manager - A Git-based package manager for Claude agents"
license = "MIT"
repository = "https://github.com/yourusername/ccpm"
readme = "README.md"
keywords = ["claude", "ai", "package-manager", "agent", "cli"]
categories = ["command-line-utilities", "development-tools"]

[features]
default = []
test-utils = []

[dependencies]
clap = { version = "4.5", features = ["derive", "cargo", "env"] }
tokio = { version = "1.40", features = ["full"] }
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
anyhow = "1.0"
thiserror = "1.0"
colored = "2.1"
dirs = "5.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
indicatif = "0.17"
tempfile = "3.10"
url = "2.5"
semver = "1.0"
shellexpand = "3.1"
which = "6.0"
uuid = { version = "1.10", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
once_cell = "1.19"
walkdir = "2.5"
sha2 = "0.10"
hex = "0.4"
regex = "1.11"
rayon = "1.10"
futures = "0.3"
fs4 = "0.13"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.10"
mockall = "0.13"
tracing-test = "0.2"
ccpm = { path = ".", features = ["test-utils"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = "z"
