name: Publish to crates.io
run-name: "Publish to crates.io (${{ fromJson(inputs.plan).announcement_tag || github.ref_name }})"

on:
  workflow_call:
    inputs:
      plan:
        description: 'dist plan from the plan job'
        required: true
        type: string

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ fromJson(inputs.plan).announcement_tag }}
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Verify build
        run: cargo build --release

      - name: Run tests
        run: cargo test --release

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          echo "📦 Publishing to crates.io for tag ${{ fromJson(inputs.plan).announcement_tag }}..."
          cargo publish --no-verify --token "$CARGO_REGISTRY_TOKEN" || {
            echo "⚠️ Failed to publish to crates.io. This might be expected for re-releases or if the version already exists."
            exit 0
          }
          echo "✅ Successfully published to crates.io!"